<!DOCTYPE html><html xmlns:v='urn:schemas-microsoft-com:vml' xmlns:o='urn:schemas-microsoft-com:office:office' lang='en'><head><title></title><meta http-equiv='Content-Type' content='text/html; charset=utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch><o:AllowPNG/></o:OfficeDocumentSettings></xml><![endif]--><!--[if !mso]><!--><link href='https://fonts.googleapis.com/css?family=Roboto' 
rel='stylesheet' type='text/css'><link href='https://fonts.googleapis.com/css?family=Abril+Fatface' rel='stylesheet' type='text/css'><link href='https://fonts.googleapis.com/css?family=Merriweather' rel='stylesheet' type='text/css'><link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'><link href='https://fonts.googleapis.com/css?family=Nunito' rel='stylesheet' type='text/css'><link href='https://fonts.googleapis.com/css?family=Bitter' rel='stylesheet' 
type='text/css'><link href='https://fonts.googleapis.com/css?family=Permanent+Marker' rel='stylesheet' type='text/css'><link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'><link href='https://fonts.googleapis.com/css?family=Cabin' rel='stylesheet' type='text/css'><link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'><link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'><link
 href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'><link href='https://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'><link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'><link href='https://fonts.googleapis.com/css?family=Droid+Serif' rel='stylesheet' type='text/css'><link href='https://fonts.googleapis.com/css?family=Playfair+Display' rel='stylesheet' type='text/css'><link 
href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet' type='text/css'><!--<![endif]--><style>
*{box-sizing:border-box}body{margin:0;padding:0}a[x-apple-data-detectors]{color:inherit!important;text-decoration:inherit!important}#MessageViewBody a{color:inherit;text-decoration:none}p{line-height:inherit}.desktop_hide,.desktop_hide table{mso-hide:all;display:none;max-height:0;overflow:hidden}@media (max-width:700px){.desktop_hide table.icons-inner{display:inline-block!important}.icons-inner{text-align:center}.icons-inner td{margin:0 auto}.fullMobileWidth,.row-content{width:100%!important}.mobile_hide{display:none}.stack .column{width:100%;display:block}.mobile_hide{min-height:0;max-height:0;max-width:0;overflow:hidden;font-size:0}.desktop_hide,.desktop_hide table{display:table!important;max-height:none!important}.row-5 .column-1 .block-2.heading_block h2,.row-9 .column-1 .block-1.heading_block h2{font-size:20px!important}.row-5 .column-1 .block-1.heading_block h3{font-size:26px!important}.row-4 .column-1 .block-1.paragraph_block td.pad{padding:5px 30px!important}.row-2 .column-1 .block-2.heading_block td.pad{padding:10px 60px 30px!important}.row-2 .column-1 .block-2.heading_block h1{font-size:33px!important}.row-6 .column-2{padding:30px 30px 30px 50px!important}}
</style></head><body style='margin:0;background-color:#1a30eb;padding:0;-webkit-text-size-adjust:none;text-size-adjust:none'><table class='nl-container' width='100%' border='0' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0;background-color:#1a30eb'><tbody><tr><td><table class='row row-1' align='center' width='100%' border='0' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0'><tbody><tr><td><table 
class='row-content' align='center' border='0' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0;background-color:#1a30eb;color:#000;width:680px' width='680'><tbody><tr><td class='column column-1' width='100%' style='mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;padding-top:20px;padding-bottom:10px;border-top:0;border-right:0;border-bottom:0;border-left:0'><table class='icons_block block-1' width='100%' 
border='0' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0'><tr><td class='pad' style='vertical-align:middle;color:#000;text-align:center;font-family:inherit;font-size:14px'><table class='alignment' cellpadding='0' cellspacing='0' role='presentation' align='center' style='mso-table-lspace:0;mso-table-rspace:0'><tr><td style='vertical-align:middle;text-align:center;padding-top:20px;padding-bottom:20px;padding-left:20px;padding-right:20px'><img 
class='icon' src='https://d1oco4z2z1fhwp.cloudfront.net/templates/default/7311/Logo.png' alt height='32' width='120' align='center' style='display:block;height:auto;margin:0 auto;border:0'></td></tr></table></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class='row row-2' align='center' width='100%' border='0' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0;background-size:auto'><tbody><tr><td><table 
class='row-content stack' align='center' border='0' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0;background-size:auto;background-color:#fff;color:#000;border-top:0 solid #fff;border-right:0 solid #fff;border-left:0 solid #fff;border-bottom:0 solid #fff;border-radius:30px 30px 0 0;width:680px' width='680'><tbody><tr><td class='column column-1' width='100%' 
style='mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;padding-top:0;padding-bottom:0;border-top:0;border-right:0;border-bottom:0;border-left:0'><table class='heading_block block-2' width='100%' border='0' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0'><tr><td class='pad' style='width:100%;text-align:center;padding-top:70px;padding-right:60px;padding-bottom:30px;padding-left:60px'><h1 
style='margin:0;color:#020b22;font-size:40px;font-family:Poppins,Arial,Helvetica,sans-serif;line-height:150%;text-align:center;direction:ltr;font-weight:700;letter-spacing:normal;margin-top:0;margin-bottom:0'><span class='tinyMce-placeholder'>Are we friends on social media?</span></h1></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class='row row-3' align='center' width='100%' border='0' cellpadding='0' cellspacing='0' role='presentation' 
style='mso-table-lspace:0;mso-table-rspace:0'><tbody><tr><td><table class='row-content stack' align='center' border='0' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0;background-color:#fff;color:#000;width:680px' width='680'><tbody><tr><td class='column column-1' width='100%' 
style='mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;padding-top:0;padding-bottom:0;border-top:0;border-right:0;border-bottom:0;border-left:0'><table class='image_block block-1' width='100%' border='0' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0'><tr><td class='pad' style='width:100%;padding-right:0;padding-left:0'><div class='alignment' align='center' style='line-height:10px'><img 
class='fullMobileWidth' src='https://d1oco4z2z1fhwp.cloudfront.net/templates/default/7311/brand_awarenes.png' style='display:block;height:auto;border:0;width:442px;max-width:100%' width='442' alt='Social profile' title='Social profile'></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class='row row-4' align='center' width='100%' border='0' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0'><tbody><tr><td><table 
class='row-content stack' align='center' border='0' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0;background-color:#fff;color:#000;width:680px' width='680'><tbody><tr><td class='column column-1' width='100%' style='mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;padding-top:0;padding-bottom:60px;border-top:0;border-right:0;border-bottom:0;border-left:0'><table class='paragraph_block block-1' width='100%' 
border='0' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0;word-break:break-word'><tr><td class='pad' style='padding-top:5px;padding-right:60px;padding-bottom:5px;padding-left:60px'><div style='color:#878787;font-size:16px;font-family:Poppins,Arial,Helvetica,sans-serif;font-weight:400;line-height:120%;text-align:center;direction:ltr;letter-spacing:0;mso-line-height-alt:19.2px'><p style='margin:0'>
Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis</p></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class='row row-5' align='center' width='100%' border='0' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0'><tbody><tr><td><table 
class='row-content stack' align='center' border='0' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0;background-color:#fff;color:#000;width:680px' width='680'><tbody><tr><td class='column column-1' width='100%' style='mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-left:50px;padding-right:50px;vertical-align:top;padding-top:0;padding-bottom:40px;border-top:0;border-right:0;border-bottom:0;border-left:0'><table 
class='heading_block block-1' width='100%' border='0' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0'><tr><td class='pad' style='width:100%;text-align:center;padding-top:5px;padding-bottom:5px'><h3 style='margin:0;color:#1a30eb;font-size:30px;font-family:Poppins,Arial,Helvetica,sans-serif;line-height:120%;text-align:center;direction:ltr;font-weight:400;letter-spacing:normal;margin-top:0;margin-bottom:0'>
<span class='tinyMce-placeholder'>Connect with us</span></h3></td></tr></table><table class='heading_block block-2' width='100%' border='0' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0'><tr><td class='pad' style='width:100%;text-align:center;padding-top:5px;padding-bottom:10px'><h2 
style='margin:0;color:#878787;font-size:26px;font-family:Poppins,Arial,Helvetica,sans-serif;line-height:120%;text-align:center;direction:ltr;font-weight:700;letter-spacing:normal;margin-top:0;margin-bottom:0'><span class='tinyMce-placeholder'>We promise to share only cool stuff! 🤞🏻</span></h2></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class='row row-6' align='center' width='100%' border='0' cellpadding='0' cellspacing='0' role='presentation' 
style='mso-table-lspace:0;mso-table-rspace:0'><tbody><tr><td><table class='row-content stack' align='center' border='0' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0;background-color:#f2f5ff;color:#000;border-radius:0;width:680px' width='680'><tbody><tr><td class='column column-1' width='50%' 
style='mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;border-bottom:1px solid #1a30eb;border-top:1px solid #1a30eb;padding-left:45px;padding-right:25px;vertical-align:top;border-right:0;border-left:0'><table class='image_block block-3' width='100%' border='0' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0'><tr><td class='pad' style='width:100%;padding-right:0;padding-left:0;padding-top:60px;padding-bottom:30px'><div 
class='alignment' align='center' style='line-height:10px'><img src='https://d1oco4z2z1fhwp.cloudfront.net/templates/default/7311/post.png' style='display:block;height:auto;border:0;width:270px;max-width:100%' width='270' alt='Post' title='Post'></div></td></tr></table></td><td class='column column-2' width='50%' 
style='mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;border-bottom:1px solid #1a30eb;border-left:0 solid #1a30eb;border-top:1px solid #1a30eb;padding-left:30px;padding-right:30px;vertical-align:top;border-right:0'><table class='text_block block-2' width='100%' border='0' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0;word-break:break-word'><tr><td class='pad' 
style='padding-bottom:45px;padding-left:5px;padding-right:30px;padding-top:70px'><div style='font-family:sans-serif'><div class='txtTinyMce-wrapper' style='font-size:12px;mso-line-height-alt:14.399999999999999px;color:#353d46;line-height:1.2;font-family:Poppins,Arial,Helvetica,sans-serif'><p style='margin:0;font-size:14px;text-align:left'><span style='font-size:20px;'><span style='color:#1a30eb;'>&gt; </span>Get to know the latest tech news on Twitter</span><br><br>
<span style='font-size:20px;'><span style='color:#1a30eb;'>&gt;</span> Shop direct on our Instagram page</span><br><br><span style='font-size:20px;'><span style='color:#1a30eb;'>&gt; </span>Stay tuned about our deals and promotions on Facebook</span></p></div></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class='row row-7' align='center' width='100%' border='0' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0'>
<tbody><tr><td><table class='row-content stack' align='center' border='0' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0;background-color:#fff;color:#000;width:680px' width='680'><tbody><tr><td class='column column-1' width='100%' 
style='mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-left:50px;padding-right:50px;vertical-align:top;padding-top:40px;padding-bottom:0;border-top:0;border-right:0;border-bottom:0;border-left:0'><table class='text_block block-1' width='100%' border='0' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0;word-break:break-word'><tr><td class='pad' 
style='padding-bottom:15px;padding-left:30px;padding-right:30px;padding-top:10px'><div style='font-family:sans-serif'><div class='txtTinyMce-wrapper' style='font-size:12px;mso-line-height-alt:14.399999999999999px;color:#888;line-height:1.2;font-family:Poppins,Arial,Helvetica,sans-serif'><p style='margin:0;font-size:14px;text-align:center'><span style='font-size:20px;'>Search for our profile</span></p></div></div></td></tr></table><table class='heading_block block-2' width='100%' border='0' 
cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0'><tr><td class='pad' style='width:100%;text-align:center;padding-top:15px;padding-bottom:15px'><h3 style='margin:0;color:#020b22;font-size:24px;font-family:Poppins,Arial,Helvetica,sans-serif;line-height:120%;text-align:center;direction:ltr;font-weight:400;letter-spacing:normal;margin-top:0;margin-bottom:0'>
<strong><span class='tinyMce-placeholder'><span id='05276ec3-3f46-45fb-8f44-d2df8fd334b8'>@TopTech</span></span></strong></h3></td></tr></table><table class='text_block block-3' width='100%' border='0' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0;word-break:break-word'><tr><td class='pad' style='padding-bottom:15px;padding-left:5px;padding-right:30px;padding-top:10px'><div style='font-family:sans-serif'><div class='txtTinyMce-wrapper' 
style='font-size:12px;mso-line-height-alt:14.399999999999999px;color:#888;line-height:1.2;font-family:Poppins,Arial,Helvetica,sans-serif'><p style='margin:0;font-size:14px;text-align:center'><span style='font-size:20px;'>or click on the links below</span></p></div></div></td></tr></table><table class='image_block block-4' width='100%' border='0' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0'><tr><td class='pad' 
style='width:100%;padding-right:0;padding-left:0'><div class='alignment' align='center' style='line-height:10px'><img src='https://d1oco4z2z1fhwp.cloudfront.net/templates/default/7311/social-media.gif' style='display:block;height:auto;border:0;width:170px;max-width:100%' width='170' alt='Likes' title='Likes'></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class='row row-8' align='center' width='100%' border='0' cellpadding='0' cellspacing='0' 
role='presentation' style='mso-table-lspace:0;mso-table-rspace:0'><tbody><tr><td><table class='row-content stack' align='center' border='0' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0;background-color:#fff;color:#000;border-radius:0;width:680px' width='680'><tbody><tr><td class='column column-1' width='33.333333333333336%' 
style='mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;background-color:#c13584;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0'><table class='icons_block block-2' width='100%' border='0' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0'><tr><td class='pad' 
style='vertical-align:middle;color:#fff;text-align:center;padding-top:25px;padding-right:20px;padding-bottom:25px;padding-left:20px;font-family:inherit;font-size:16px'><table width='100%' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0'><tr><td class='alignment' style='vertical-align:middle;text-align:center'>
<!--[if vml]><table align='left' cellpadding='0' cellspacing='0' role='presentation' style='display:inline-block;padding-left:0px;padding-right:0px;mso-table-lspace: 0pt;mso-table-rspace: 0pt;'><![endif]--><!--[if !vml]><!--><table class='icons-inner' style='mso-table-lspace:0;mso-table-rspace:0;display:inline-block;margin-right:-4px;padding-left:0;padding-right:0' cellpadding='0' cellspacing='0' role='presentation'><!--<![endif]--><tr><td 
style='vertical-align:middle;text-align:center;padding-top:10px;padding-bottom:25px;padding-left:10px;padding-right:10px'><a href='https://www.example.com' target='_self' style='text-decoration: none;'><img class='icon' alt='Instagram' src='https://d1oco4z2z1fhwp.cloudfront.net/templates/default/7311/insta.png' height='32' width='32' align='center' style='display:block;height:auto;margin:0 auto;border:0'></a></td></tr><tr><td 
style='font-family:Poppins,Arial,Helvetica,sans-serif;font-size:16px;color:#fff;vertical-align:middle;letter-spacing:undefined;text-align:center'><a href='https://www.example.com' target='_self' style='color: #ffffff; text-decoration: none;'>Instagram</a></td></tr></table></td></tr></table></td></tr></table></td><td class='column column-2' width='33.333333333333336%' 
style='mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;background-color:#6386e0;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0'><table class='icons_block block-2' width='100%' border='0' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0'><tr><td class='pad' 
style='vertical-align:middle;color:#fff;text-align:center;padding-top:25px;padding-right:20px;padding-bottom:25px;padding-left:20px;font-family:inherit;font-size:16px'><table width='100%' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0'><tr><td class='alignment' style='vertical-align:middle;text-align:center'>
<!--[if vml]><table align='left' cellpadding='0' cellspacing='0' role='presentation' style='display:inline-block;padding-left:0px;padding-right:0px;mso-table-lspace: 0pt;mso-table-rspace: 0pt;'><![endif]--><!--[if !vml]><!--><table class='icons-inner' style='mso-table-lspace:0;mso-table-rspace:0;display:inline-block;margin-right:-4px;padding-left:0;padding-right:0' cellpadding='0' cellspacing='0' role='presentation'><!--<![endif]--><tr><td 
style='vertical-align:middle;text-align:center;padding-top:10px;padding-bottom:25px;padding-left:10px;padding-right:10px'><a href='https://www.example.com' target='_self' style='text-decoration: none;'><img class='icon' alt='Facebook' src='https://d1oco4z2z1fhwp.cloudfront.net/templates/default/7311/facebook.png' height='32' width='18' align='center' style='display:block;height:auto;margin:0 auto;border:0'></a></td></tr><tr><td 
style='font-family:Poppins,Arial,Helvetica,sans-serif;font-size:16px;color:#fff;vertical-align:middle;letter-spacing:undefined;text-align:center'><a href='https://www.example.com' target='_self' style='color: #ffffff; text-decoration: none;'>Facebook</a></td></tr></table></td></tr></table></td></tr></table></td><td class='column column-3' width='33.333333333333336%' 
style='mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;background-color:#7bc8ff;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0'><table class='icons_block block-2' width='100%' border='0' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0'><tr><td class='pad' 
style='vertical-align:middle;color:#fff;text-align:center;padding-top:25px;padding-right:20px;padding-bottom:25px;padding-left:20px;font-family:inherit;font-size:16px'><table width='100%' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0'><tr><td class='alignment' style='vertical-align:middle;text-align:center'>
<!--[if vml]><table align='left' cellpadding='0' cellspacing='0' role='presentation' style='display:inline-block;padding-left:0px;padding-right:0px;mso-table-lspace: 0pt;mso-table-rspace: 0pt;'><![endif]--><!--[if !vml]><!--><table class='icons-inner' style='mso-table-lspace:0;mso-table-rspace:0;display:inline-block;margin-right:-4px;padding-left:0;padding-right:0' cellpadding='0' cellspacing='0' role='presentation'><!--<![endif]--><tr><td 
style='vertical-align:middle;text-align:center;padding-top:10px;padding-bottom:25px;padding-left:10px;padding-right:10px'><a href='https://www.example.com' target='_self' style='text-decoration: none;'><img class='icon' alt='Twitter' src='https://d1oco4z2z1fhwp.cloudfront.net/templates/default/7311/twitter.png' height='32' width='32' align='center' style='display:block;height:auto;margin:0 auto;border:0'></a></td></tr><tr><td 
style='font-family:Poppins,Arial,Helvetica,sans-serif;font-size:16px;color:#fff;vertical-align:middle;letter-spacing:undefined;text-align:center'><a href='https://www.example.com' target='_self' style='color: #ffffff; text-decoration: none;'>Twitter</a></td></tr></table></td></tr></table></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class='row row-9' align='center' width='100%' border='0' cellpadding='0' cellspacing='0' role='presentation' 
style='mso-table-lspace:0;mso-table-rspace:0'><tbody><tr><td><table class='row-content stack' align='center' border='0' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0;background-color:#f2f5ff;color:#000;border-radius:0 0 30px 30px;width:680px' width='680'><tbody><tr><td class='column column-1' width='100%' 
style='mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;padding-top:15px;padding-bottom:15px;border-top:0;border-right:0;border-bottom:0;border-left:0'><table class='heading_block block-1' width='100%' border='0' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0'><tr><td class='pad' style='width:100%;text-align:center;padding-top:20px;padding-bottom:20px'><h2 
style='margin:0;color:#1a30eb;font-size:20px;font-family:Poppins,Arial,Helvetica,sans-serif;line-height:120%;text-align:center;direction:ltr;font-weight:700;letter-spacing:normal;margin-top:0;margin-bottom:0'><span class='tinyMce-placeholder'>Don't be out. Join us.</span></h2></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class='row row-10' align='center' width='100%' border='0' cellpadding='0' cellspacing='0' role='presentation' 
style='mso-table-lspace:0;mso-table-rspace:0'><tbody><tr><td><table class='row-content stack' align='center' border='0' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0;background-color:#1a30eb;color:#000;width:680px' width='680'><tbody><tr><td class='column column-1' width='100%' 
style='mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;padding-top:25px;padding-bottom:25px;border-top:0;border-right:0;border-bottom:0;border-left:0'><table class='text_block block-1' width='100%' border='0' cellpadding='20' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0;word-break:break-word'><tr><td class='pad'><div style='font-family:sans-serif'><div class='txtTinyMce-wrapper' 
style='font-size:12px;font-family:Poppins,Arial,Helvetica,sans-serif;mso-line-height-alt:18px;color:#fafafa;line-height:1.5'><p style='margin:0;font-size:10px;text-align:center;font-family:inherit;mso-line-height-alt:15px'><span style='font-size:10px;'><span style>© 2022 Company.&nbsp;</span></span><span style='font-size:10px;'><span style> All Rights Reserved.</span></span></p></div></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class='row row-11' 
align='center' width='100%' border='0' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0'><tbody><tr><td><table class='row-content stack' align='center' border='0' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0;color:#000;width:680px' width='680'><tbody><tr><td class='column column-1' width='100%' 
style='mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;padding-top:5px;padding-bottom:5px;border-top:0;border-right:0;border-bottom:0;border-left:0'><table class='icons_block block-1' width='100%' border='0' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0'><tr><td class='pad' style='vertical-align:middle;color:#9d9d9d;font-family:inherit;font-size:15px;padding-bottom:5px;padding-top:5px;text-align:center'>
<table width='100%' cellpadding='0' cellspacing='0' role='presentation' style='mso-table-lspace:0;mso-table-rspace:0'><tr><td class='alignment' style='vertical-align:middle;text-align:center'><!--[if vml]><table align='left' cellpadding='0' cellspacing='0' role='presentation' style='display:inline-block;padding-left:0px;padding-right:0px;mso-table-lspace: 0pt;mso-table-rspace: 0pt;'><![endif]--><!--[if !vml]><!--><table class='icons-inner' 
style='mso-table-lspace:0;mso-table-rspace:0;display:inline-block;margin-right:-4px;padding-left:0;padding-right:0' cellpadding='0' cellspacing='0' role='presentation'><!--<![endif]--><tr><td style='vertical-align:middle;text-align:center;padding-top:5px;padding-bottom:5px;padding-left:5px;padding-right:6px'><a href='https://www.designedwithbee.com/' target='_blank' style='text-decoration: none;'><img class='icon' alt='Designed with BEE' 
src='https://d15k2d11r6t6rl.cloudfront.net/public/users/Integrators/BeeProAgency/53601_510656/Signature/bee.png' height='32' width='34' align='center' style='display:block;height:auto;margin:0 auto;border:0'></a></td><td style='font-family:Poppins,Arial,Helvetica,sans-serif;font-size:15px;color:#9d9d9d;vertical-align:middle;letter-spacing:undefined;text-align:center'>
<a href='https://www.designedwithbee.com/' target='_blank' style='color: #9d9d9d; text-decoration: none;'>Designed with BEE</a></td></tr></table></td></tr></table></td></tr></table></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table><!-- End --></body></html>